### PR TITLE
Add ability to execute without td

### PR DESCRIPTION
**Pull request by ishammahajan**
selfie-2
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

- [x] Add related code to exec.bat
- [x] Edit README.md accordingly!

### CODE REVIEW

**Comment by ishammahajan** [comment]
> selfie-2
> [_GitHub Selfies_](https://github.com/thieman/github-selfies/)
> 
> * [x]  Add related code to exec.bat
> * [x]  Edit README.md accordingly!

**Comment by ishammahajan** [comment]
- [x]  Add related code to exec.bat
- [x]  Edit README.md accordingly!

**Comment by CryoScythe** [comment]
Rename ```-oe``` to ```oe``` for the sake of code clarity

**Comment by CryoScythe** [comment]
Also the flow executes td and normal exe when no argument is passed

**Comment by ishammahajan** [comment]
How about exoe? It'll simplify the process more and perhaps bring more clarity.

**Comment by ishammahajan** [comment]
Rebased

**Comment by ishammahajan** [comment]
Squash from your end, not able to figure out how to fix that mistake in 15df5a1.

**Pull request closed without merging**
